name: CI and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Build on an Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        npm install  # Clean install dependencies

    - name: Build the project
      run: |
        npm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build  # Upload the 'build' directory

  deploy:
    runs-on: self-hosted  # Deploy on your self-hosted runner
    needs: build  # Ensure the build job completes first

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build  # Match the artifact name from the build job

    - name: Deploy to EC2 and restart Nginx
      run: |
        # Copy the downloaded build directory to the EC2 instance directory
        sudo cp -r ./build /var/www/vhosts/zeezahome/
        
        # Restart Nginx
        sudo systemctl restart nginx
