name: Node.js CI and Deploy

on:
  push:
    branches: [ "master" ]  # Trigger the workflow on push to the master branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    - name: Build
      run: |
        npm run build

    - name: Deploy to EC2 and restart Nginx
      run: |
        # Copy the build directory to the EC2 instance directory
        sudo cp -r ./build /var/www/vhosts/zeezahome/
        
        # Restart Nginx
        sudo systemctl restart nginx
