name: ESLint Check  

on:  
  push:  
    branches: [ "master" ]  

jobs:  
  lint:  
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner  

    steps:  
      # Step 1: Checkout repository  
      - name: Checkout repository  
        uses: actions/checkout@v4  

      # Step 2: Install dependencies  
      - name: Install dependencies  
        run: |  
          npm install  # Clean install dependencies  

      # Step 3: Run ESLint  
      - name: Run ESLint  
        run: |  
          npm run lint  
